### PR TITLE
Fix "cannot range over" local lint errors

### PR DESCRIPTION
**Pull request by mpryc**
Fix for the "cannot range over" that bumps the golang-ci version Makes simila range loop in the nab controller.

## Why the changes were made

To fix local $ make lint errors introduced with https://github.com/migtools/oadp-non-admin/pull/122

New version of golang-ci is fixing the issue on local ran.

## How to test the changes made

ran the lint after change, no error appeared.

This PR is similar to #124, but uses different approach, so one or other should be merged.

### CODE REVIEW

**Comment by mpryc** [comment]
@kaovilai FYI

**Review by mateusoliveira43 — CHANGES_REQUESTED** [review]
need to change here https://github.com/migtools/oadp-non-admin/blob/2113181193f1b549482ce1d5a5b985b52e94d2d2/.golangci.yml#L1

**Review by kaovilai — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
Why did I not have issue with 1.56.2 tho.. 🤷 

https://github.com/migtools/oadp-non-admin/pull/124#pullrequestreview-2479278049

**Review by mateusoliveira43 — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
@kaovilai https://github.com/migtools/oadp-non-admin/pull/124#issuecomment-2517847473

Michal's executable was built with go 1.21, mine and yours with 1.22

**Comment by kaovilai** [comment]
Too bad.. I think you should avoid using go install for linters.. that would solve this issue . That meant this PR is no-op.

**Comment by kaovilai** [comment]
perhaps the makefile should set GOTOOLCHAIN, and only then can the `make lint` be reliable :D

https://go.dev/doc/toolchain

**Pull request merged**
